import { describe, it, expect, beforeEach, vi, afterEach } from 'vitest';
import { synth } from '../synth.js';
import { Job } from '../../constructs/Job.js';
import { Rule } from '../../constructs/Rule.js';
import { Cache } from '../../constructs/Cache.js';
import { Artifact } from '../../constructs/Artifact.js';
import { Default } from '../../constructs/Default.js';

describe('synth', () => {
  beforeEach(() => {
    vi.useFakeTimers();
    vi.setSystemTime(new Date('2024-01-01T00:00:00.000Z'));
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  it('should synthesize a simple job', () => {
    const jobs = {
      test: new Job({
        script: ['npm test']
      })
    };

    const yaml = synth(jobs);

    expect(yaml).toContain('# This file was automatically generated by GitLab CI Kit');
    expect(yaml).toContain('# Generated: 2024-01-01T00:00:00.000Z');
    expect(yaml).toContain('test:');
    expect(yaml).toContain('script:');
    expect(yaml).toContain('- npm test');
  });

  it('should synthesize multiple jobs', () => {
    const jobs = {
      build: new Job({
        script: ['npm run build']
      }),
      test: new Job({
        script: ['npm test']
      })
    };

    const yaml = synth(jobs);

    expect(yaml).toContain('build:');
    expect(yaml).toContain('- npm run build');
    expect(yaml).toContain('test:');
    expect(yaml).toContain('- npm test');
  });

  it('should synthesize jobs with stages', () => {
    const jobs = {
      build: new Job({
        stage: 'build',
        script: ['npm run build']
      }),
      test: new Job({
        stage: 'test',
        script: ['npm test']
      })
    };

    const config = {
      stages: ['build', 'test']
    };

    const yaml = synth(jobs, config);

    expect(yaml).toContain('stages:');
    expect(yaml).toContain('- build');
    expect(yaml).toContain('- test');
  });

  it('should synthesize jobs with variables', () => {
    const jobs = {
      test: new Job({
        script: ['npm test'],
        variables: {
          NODE_ENV: 'test'
        }
      })
    };

    const yaml = synth(jobs);

    expect(yaml).toContain('variables:');
    expect(yaml).toContain('NODE_ENV: test');
  });

  it('should synthesize global variables', () => {
    const jobs = {
      test: new Job({
        script: ['npm test']
      })
    };

    const config = {
      variables: {
        GLOBAL_VAR: 'value',
        DEBUG: true
      }
    };

    const yaml = synth(jobs, config);

    expect(yaml).toContain('variables:');
    expect(yaml).toContain('GLOBAL_VAR: value');
    expect(yaml).toContain('DEBUG: true');
  });

  it('should unwrap Rule constructs', () => {
    const jobs = {
      deploy: new Job({
        script: ['npm run deploy'],
        rules: [
          new Rule({
            if: '$CI_COMMIT_BRANCH == "main"',
            when: 'manual'
          })
        ]
      })
    };

    const yaml = synth(jobs);

    expect(yaml).toContain('rules:');
    expect(yaml).toContain('if: $CI_COMMIT_BRANCH == "main"');
    expect(yaml).toContain('when: manual');
  });

  it('should unwrap Cache constructs', () => {
    const jobs = {
      test: new Job({
        script: ['npm test'],
        cache: new Cache({
          key: 'npm-cache',
          paths: ['node_modules/']
        })
      })
    };

    const yaml = synth(jobs);

    expect(yaml).toContain('cache:');
    expect(yaml).toContain('key: npm-cache');
    expect(yaml).toContain('paths:');
    expect(yaml).toContain('- node_modules/');
  });

  it('should unwrap Artifact constructs', () => {
    const jobs = {
      build: new Job({
        script: ['npm run build'],
        artifacts: new Artifact({
          paths: ['dist/'],
          expire_in: '1 week'
        })
      })
    };

    const yaml = synth(jobs);

    expect(yaml).toContain('artifacts:');
    expect(yaml).toContain('paths:');
    expect(yaml).toContain('- dist/');
    expect(yaml).toContain('expire_in: 1 week');
  });

  it('should unwrap Default construct', () => {
    const jobs = {
      test: new Job({
        script: ['npm test']
      })
    };

    const config = {
      default: new Default({
        image: 'node:20',
        before_script: ['npm install']
      })
    };

    const yaml = synth(jobs, config);

    expect(yaml).toContain('default:');
    expect(yaml).toContain('image: node:20');
    expect(yaml).toContain('before_script:');
    expect(yaml).toContain('- npm install');
  });

  it('should handle workflow configuration', () => {
    const jobs = {
      test: new Job({
        script: ['npm test']
      })
    };

    const config = {
      workflow: {
        name: 'My Pipeline',
        rules: [
          new Rule({
            if: '$CI_COMMIT_BRANCH'
          })
        ]
      }
    };

    const yaml = synth(jobs, config);

    expect(yaml).toContain('workflow:');
    expect(yaml).toContain('name: My Pipeline');
    expect(yaml).toContain('rules:');
  });

  it('should handle include configuration', () => {
    const jobs = {
      test: new Job({
        script: ['npm test']
      })
    };

    const config = {
      include: [
        { local: '.gitlab/workflows/common.yml' },
        { template: 'Security/SAST.gitlab-ci.yml' }
      ]
    };

    const yaml = synth(jobs, config);

    expect(yaml).toContain('include:');
    expect(yaml).toContain('local: .gitlab/workflows/common.yml');
    expect(yaml).toContain('template: Security/SAST.gitlab-ci.yml');
  });

  it('should handle nested constructs in arrays', () => {
    const jobs = {
      test: new Job({
        script: ['npm test'],
        rules: [
          new Rule({ if: '$CI_COMMIT_BRANCH == "main"' }),
          new Rule({ if: '$CI_COMMIT_TAG' })
        ]
      })
    };

    const yaml = synth(jobs);

    expect(yaml).toContain('if: $CI_COMMIT_BRANCH == "main"');
    expect(yaml).toContain('if: $CI_COMMIT_TAG');
  });

  it('should handle workflow with autoCancel', () => {
    const jobs = {
      test: new Job({
        script: ['npm test']
      })
    };

    const config = {
      workflow: {
        autoCancel: {
          onNewCommit: 'interruptible' as const,
          onJobFailure: 'all' as const
        }
      }
    };

    const yaml = synth(jobs, config);

    expect(yaml).toContain('workflow:');
    expect(yaml).toContain('autoCancel:');
    expect(yaml).toContain('onNewCommit: interruptible');
    expect(yaml).toContain('onJobFailure: all');
  });

  it('should handle complex nested structures', () => {
    const jobs = {
      deploy: new Job({
        script: ['npm run deploy'],
        stage: 'deploy',
        cache: new Cache({
          key: {
            files: ['package-lock.json']
          },
          paths: ['node_modules/']
        }),
        artifacts: new Artifact({
          paths: ['dist/'],
          exclude: ['*.log']
        }),
        rules: [
          new Rule({
            if: '$CI_COMMIT_BRANCH == "main"',
            variables: {
              DEPLOY_ENV: 'production'
            }
          })
        ]
      })
    };

    const config = {
      stages: ['build', 'test', 'deploy'],
      variables: {
        NODE_ENV: 'production'
      },
      default: new Default({
        image: 'node:20',
        retry: 2
      })
    };

    const yaml = synth(jobs, config);

    expect(yaml).toContain('stages:');
    expect(yaml).toContain('variables:');
    expect(yaml).toContain('NODE_ENV: production');
    expect(yaml).toContain('default:');
    expect(yaml).toContain('image: node:20');
    expect(yaml).toContain('retry: 2');
    expect(yaml).toContain('deploy:');
    expect(yaml).toContain('cache:');
    expect(yaml).toContain('artifacts:');
    expect(yaml).toContain('rules:');
  });

  it('should produce valid YAML format', () => {
    const jobs = {
      test: new Job({
        script: ['npm test']
      })
    };

    const yaml = synth(jobs);

    expect(yaml).toMatch(/^# This file was automatically generated/);
    expect(yaml).toContain('\n');
    expect(yaml.split('\n').length).toBeGreaterThan(5);
  });

  it('should handle empty jobs object', () => {
    const jobs = {};

    const yaml = synth(jobs);

    expect(yaml).toContain('# This file was automatically generated by GitLab CI Kit');
    expect(yaml).toContain('# Generated: 2024-01-01T00:00:00.000Z');
  });

  it('should handle jobs without config', () => {
    const jobs = {
      simple: new Job({
        script: ['echo "Hello"']
      })
    };

    const yaml = synth(jobs);

    expect(yaml).toContain('simple:');
    expect(yaml).toContain('script:');
    expect(yaml).toContain('- echo "Hello"');
  });
});
