import { stringify } from 'yaml';
import snakecaseKeys from 'snakecase-keys'
import type { Job } from '../constructs/Job.js';
import type { Rule } from '../constructs/Rule.js';
import type { Default } from '../constructs/Default.js';
import { packageUpSync } from 'package-up';
import { writeFileSync } from 'node:fs';

/**
 * Configuration for the pipeline (top-level GitLab CI properties).
 */
export interface PipelineConfig {
  variables?: Record<string, string | number | boolean>;
  stages?: string[];
  workflow?: {
    name?: string;
    autoCancel?: {
      onNewCommit?: 'conservative' | 'interruptible' | 'none';
      onJobFailure?: 'none' | 'all';
    };
    rules?: Array<Rule | string | string[]>;
  };
  default?: Default;
  include?: Array<string | { local?: string; project?: string; ref?: string; file?: string | string[]; template?: string; remote?: string }>;
  write?: boolean;
}

/**
 * Converts construct instances to their underlying props.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function unwrapConstruct(value: any): any {
  if (!value) return value;

  // Handle arrays
  if (Array.isArray(value)) {
    return value.map(unwrapConstruct);
  }

  // Handle construct instances (Job, Rule, Cache, Artifact)
  if (value.props !== undefined) {
    return unwrapConstruct(value.props);
  }

  // Handle objects recursively
  if (typeof value === 'object') {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const result: any = {};
    for (const [key, val] of Object.entries(value)) {
      result[key] = unwrapConstruct(val);
    }
    return result;
  }

  return value;
}

/**
 * Synthesizes a GitLab CI pipeline to YAML.
 * 
 * @param jobs - Object mapping job names to Job instances
 * @param config - Optional pipeline-level configuration
 * @returns YAML string
 */
export function synth(
  jobs: Record<string, Job>,
  config: PipelineConfig = {
    write: true
  }
) {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const pipeline: Record<string, any> = {};

  // Add top-level config
  if (config) {
    const unwrapped = unwrapConstruct(config);
    Object.assign(pipeline, snakecaseKeys(unwrapped));
  }

  // Add jobs
  for (const [name, job] of Object.entries(jobs)) {
    const unwrapped = unwrapConstruct(job.props);
    pipeline[name] = snakecaseKeys(unwrapped);
  }

  // Generate YAML
  const yaml = stringify(pipeline, {
    lineWidth: 0,
    defaultStringType: 'PLAIN',
    defaultKeyType: 'PLAIN',
    nullStr: 'null',
  });

  // Add header comment
  const header = `# This file was automatically generated by GitLab CI Kit
# Generated: ${new Date().toISOString()}
# DO NOT EDIT MANUALLY - Changes will be overwritten

`;

  const output = header + yaml

  if (config.write || typeof config.write === 'undefined') {
    const pkgPath = packageUpSync()

    if (!pkgPath) {
      console.log("WARN: package.json not found")
      return output;
    }

    const outPath = pkgPath.replace('package.json', '.gitlab-ci.yml')
    console.log({ outPath })
    writeFileSync(outPath, output, 'utf-8')
  }

  return header + yaml;
}
